platform :ios, '10.0'

source 'https://github.com/wobbals/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'S3FileSharing_Example' do
  pod 'S3FileSharing', :path => '../'
  pod 'OpenTok'
end

target 'S3FileSharing_Tests' do
  pod 'S3FileSharing', :path => '../'
end

