platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'S3FileSharing_Example' do
  pod 'S3FileSharing', :path => '../'
end

target 'S3FileSharing_Tests' do
  pod 'S3FileSharing', :path => '../'
end

