platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'S3FileSharing_Example', :exclusive => true do
  pod 'S3FileSharing', :path => '../'
end

target 'S3FileSharing_Tests', :exclusive => true do
  pod 'S3FileSharing', :path => '../'

  
end
